/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 my_room.glb
Model: "My room" by Oleaf (https://sketchfab.com/homkahom0)
Source: https://sketchfab.com/3d-models/my-room-109790fce06a4ff3b4b96c2c2cfcc33e
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { EffectComposer, SelectiveBloom } from "@react-three/postprocessing";
import { BlendFunction } from "postprocessing";
import * as THREE from "three";
import type { ThreeElements } from "@react-three/fiber";
import type { Group, Mesh } from "three";
import type { GLTF } from "three-stdlib";

type RoomGLTFResult = GLTF & {
  nodes: {
    comp_blinn1_0: Mesh;
    triangle_blinn1_0: Mesh;
    keyboard_blinn1_0: Mesh;
    railing_blinn1_0: Mesh;
    table_blinn1_0: Mesh;
    cabin_blinn1_0: Mesh;
    lamp_emis_blinn1_0: Mesh;
    kovrik_blinn1_0: Mesh;
    vac_black_blinn1_0: Mesh;
    miuse_blinn1_0: Mesh;
    red_vac_blinn1_0: Mesh;
    vacuum1_blinn1_0: Mesh;
    pCylinder5_blinn1_0: Mesh;
    stylus_blinn1_0: Mesh;
    vires_blinn1_0: Mesh;
    tablet_blinn1_0: Mesh;
    radiator_blinn1_0: Mesh;
    window_blinn1_0: Mesh;
    handls_blinn1_0: Mesh;
    emis_lambert1_0: Mesh;
    vacuumgrey_blinn1_0: Mesh;
    red_bttns_blinn1_0: Mesh;
    lamp_white_blinn1_0: Mesh;
    lamp_bl_blinn1_0: Mesh;
    pillows_blinn1_0: Mesh;
    polySurface53_blinn1_0: Mesh;
    chair_body_blinn1_0: Mesh;
    monitor2_blinn1_0: Mesh;
    monitor3_blinn1_0: Mesh;
    _________6_blinn1_0: Mesh;
    body1_blinn1_0: Mesh;
    window4_phong1_0: Mesh;
  };
  materials: {
    blinn1: THREE.Material;
    lambert1: THREE.Material;
    phong1: THREE.Material;
  };
};

export function Room(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/my_room.glb"
  ) as unknown as RoomGLTFResult;
  const glowRef = useRef<Group>(null!);

  // curtains — rich burgundy, warmed where the lamp/window light hits them
  const curtainMaterial = new THREE.MeshStandardMaterial({
    color: "#7a2140",
    roughness: 0.75,
  });

  // room shell (walls + floor + ceiling combined in this mesh) — the mesh
  // carries the original artist's baked-in vertex colors (warm tan walls,
  // cool navy floor/ceiling in shadow); reading those instead of a flat
  // color or a guessed texture is what actually tells the wall from the
  // floor, since they're one mesh with no per-surface UV split.
  const bodyMaterial = new THREE.MeshStandardMaterial({
    vertexColors: true,
    roughness: 0.9,
  });

  // desk surface — warm honey/caramel wood
  const tableMaterial = new THREE.MeshStandardMaterial({
    color: "#b98a5a",
    roughness: 0.45,
    metalness: 0.05,
  });

  // desk cabinet / drawers — warm mahogany-brown, matching the curtains' family
  const drawerMaterial = new THREE.MeshStandardMaterial({
    color: "#6b2f34",
    roughness: 0.6,
  });

  // radiator — warm cream-painted metal, not cool gray
  const radiatorMaterial = new THREE.MeshStandardMaterial({
    color: "#e0d3ba",
    roughness: 0.5,
    metalness: 0.2,
  });

  const compMaterial = new THREE.MeshStandardMaterial({
    color: "#fff",
  });

  // chair — matte near-black, not tinted purple
  const chairMaterial = new THREE.MeshStandardMaterial({
    color: "#1d1b1f",
    roughness: 0.55,
  });

  // night window — deep navy glass with a faint glow
  const windowMaterial = new THREE.MeshStandardMaterial({
    color: "#152048",
    emissive: "#0d1730",
    emissiveIntensity: 0.35,
    roughness: 0.2,
  });

  // monitor screens — teal/cyan glow, feeds the selective bloom
  const screenMaterial = new THREE.MeshStandardMaterial({
    color: "#8ff2d8",
    emissive: "#8ff2d8",
    emissiveIntensity: 1.2,
    toneMapped: false,
  });

  // lamp bulb — warm glow matching the desk lamp key light, also blooms
  const lampGlowMaterial = new THREE.MeshStandardMaterial({
    color: "#ff9d5c",
    emissive: "#ff9d5c",
    emissiveIntensity: 1.9,
    toneMapped: false,
  });

  return (
    // my_room.glb is an unoptimized export ~3.85x larger than the previous
    // optimized-room.glb (same source model); rescaled to match the camera
    // framing that was already tuned for the old export.
    <group {...props} scale={0.26} dispose={null}>
      <EffectComposer>
        <SelectiveBloom
          selection={glowRef}
          intensity={0.8} // Strength of the bloom
          luminanceThreshold={0.3} // Minimum luminance needed
          luminanceSmoothing={0.9} // Smooth transition
          blendFunction={BlendFunction.ADD} // How it blends
        />
      </EffectComposer>
      <mesh geometry={nodes.comp_blinn1_0.geometry} material={compMaterial} />
      <mesh
        geometry={nodes.triangle_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.keyboard_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.railing_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh geometry={nodes.table_blinn1_0.geometry} material={tableMaterial} />
      <mesh
        geometry={nodes.cabin_blinn1_0.geometry}
        material={drawerMaterial}
      />
      <mesh
        geometry={nodes.kovrik_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.vac_black_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.miuse_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.red_vac_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.vacuum1_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.pCylinder5_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.stylus_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.vires_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.tablet_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.radiator_blinn1_0.geometry}
        material={radiatorMaterial}
      />
      <mesh
        geometry={nodes.window_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.handls_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.vacuumgrey_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.red_bttns_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.lamp_white_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.lamp_bl_blinn1_0.geometry}
        material={materials.blinn1}
      />
      {/* despite the source name, this mesh is the chair's seat/backrest
          cushioning in this model — not a separate pillow prop */}
      <mesh
        geometry={nodes.pillows_blinn1_0.geometry}
        material={chairMaterial}
      />
      <mesh
        geometry={nodes.polySurface53_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.chair_body_blinn1_0.geometry}
        material={chairMaterial}
      />
      <mesh
        geometry={nodes.monitor2_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.monitor3_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes._________6_blinn1_0.geometry}
        material={curtainMaterial}
      />
      <mesh geometry={nodes.body1_blinn1_0.geometry} material={bodyMaterial} />
      <mesh
        geometry={nodes.window4_phong1_0.geometry}
        material={windowMaterial}
      />

      {/* emissive parts feeding the selective bloom: monitor screens + lamp bulb */}
      <group ref={glowRef}>
        <mesh
          geometry={nodes.emis_lambert1_0.geometry}
          material={screenMaterial}
        />
        <mesh
          geometry={nodes.lamp_emis_blinn1_0.geometry}
          material={lampGlowMaterial}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/my_room.glb");
